language: python
dist: xenial
python:
  - 3.7
install:
  - install: "pip install -r requirements.txt"
  - pip install coverage coveralls
script:
  - coverage run -m pytest tests/
after_script:
  - coveralls